import {$,esc,badge,metric,hero,api,perform,status,pretty,download} from '/shared/common.js';
let tenant='acme',role='requester',selected=null,view={workflows:[],mockRecords:0},ttl=60,limit=1;
const token=()=>`demo-${tenant}${role==='approver'?'-approver':''}`;
const current=()=>view.workflows.find(w=>w.requestId===selected);
const tone=s=>['completed','valid','approved'].includes(s)?'good':['revoked','expired','rejected','budget_exceeded'].includes(s)?'bad':'warn';
async function refresh(){view=await api('/api/control',undefined,token());if(!view.workflows.some(w=>w.requestId===selected))selected=view.workflows[0]?.requestId||null;render();}
function detail(w){if(!w)return `<div class="card empty"><strong>Make an action reviewable.</strong>Create a sales proposal to inspect its authority, execution and recovery.<p>Then try executing before approval: the engine should block it.</p></div>`;
const isSales=w.agent==='sales';return `<div class="card"><div class="card-head"><div><div class="eyebrow">SELECTED WORKFLOW · ${esc(w.agent)}</div><h2>${esc(w.requestId)}</h2></div>${badge(pretty(w.state),tone(w.state))}</div>
${w.action?`<p>${esc(w.action.summary)}</p><div class="toolbar">${badge(w.action.tool)}${badge(`${w.action.leadCount||1} requested record(s)`)}${badge(`Revision ${w.revision}`)}${badge(`${w.attempts} execution attempt(s)`)}</div>`:`<p>This ${esc(w.agent)} request does not propose a CRM write.</p>`}
${isSales?`<div class="fields"><label>Approval lifetime (seconds)<input id="ttl" type="number" min="1" max="900" value="${ttl}"></label><label>Maximum approved records<input id="limit" type="number" min="1" max="3" value="${limit}"></label></div><div class="actions"><button id="approve" class="primary">Approve proposal</button><button id="execute">Execute / replay</button><button id="reject">Reject</button><button id="revoke" class="danger">Revoke approval</button></div><div class="hint">Approval requires the approver identity. Try the requester identity to see the server reject self-approval. Execution uses the exact approved action.</div>
<div class="card-head"><div><h3>Authority at last refresh</h3>${badge(pretty(w.authority.status),tone(w.authority.status))}</div><small>${w.authority.expiresAt?`Expires ${esc(new Date(w.authority.expiresAt*1000).toLocaleTimeString())}`:'No approval granted'}</small></div><div class="digest">Proposed digest: ${esc(w.authority.actionDigest)}<br>Approved digest: ${esc(w.authority.approvedDigest||'—')}</div>
<hr class="rule"><h3>Inspect failure and recovery</h3><p>These local fault controls exercise the existing engine. The mock CRM and workflow store commit separately.</p><div class="actions"><button id="lost">Simulate lost confirmation</button><button id="timeout">Simulate pre-write timeout</button></div><p class="technical-note">After a lost confirmation, click Execute / replay. Recovery should find the existing record without another write.</p>
<details><summary>Revise the proposal</summary><label>Revised message<textarea id="revision-message">${esc(w.action.summary)}</textarea></label><label>Revised record count<input id="revision-count" type="number" min="1" max="5" value="${w.action.leadCount||1}"></label><div class="actions"><button id="revise">Save revision</button><button id="cancel">Cancel workflow</button></div><p>Revisions before execution clear the existing approval.</p></details>`:''}
${w.result?`<details ${w.state==='completed'?'open':''}><summary>Returned result</summary><pre>${esc(JSON.stringify(w.result,null,2))}</pre></details>`:''}</div>
<div class="card"><div class="card-head"><div><h2>Execution trace</h2><p>Persisted events from the reference engine.</p></div><button id="download">Download workflow</button></div><ol class="trace">${w.trace.map((t,i)=>`<li><span class="step">${i+1}</span><div><strong>${esc(pretty(t.event))}</strong>${Object.keys(t.detail).length?`<small>${esc(JSON.stringify(t.detail))}</small>`:''}</div></li>`).join('')}</ol></div>`;}
function render(){const w=current();$('#app').innerHTML=hero('01 / Agent Control Room','From proposal to permission.','Explore approval, authority and recovery through the working reference engine. Identities and CRM records are synthetic.')+
`<div class="metrics">${metric('Workflows in this tenant',view.workflows.length,'Up to 100 most recent workflows')}${metric('Awaiting approval',view.workflows.filter(w=>w.state==='awaiting_approval').length,'Human decision required')}${metric('Mock CRM records',view.mockRecords,'Counted from the connector database')}${metric('Completed workflows',view.workflows.filter(w=>w.state==='completed').length,'Includes read-only support requests')}</div>
<div class="toolbar"><label>Demo tenant<select id="tenant"><option value="acme" ${tenant==='acme'?'selected':''}>Acme</option><option value="beta" ${tenant==='beta'?'selected':''}>Beta</option></select></label><label>Demo identity<select id="role"><option value="requester" ${role==='requester'?'selected':''}>Requester</option><option value="approver" ${role==='approver'?'selected':''}>Approver</option></select></label><button id="refresh">Refresh state</button></div>
<div class="two"><div><div class="card"><h2>Create a proposal</h2><p>Start with a synthetic sales enquiry.</p><form id="new-workflow"><label>Request<textarea id="message" required maxlength="2000">Please quote a CRM integration</textarea></label><div class="fields"><label>CRM records requested<input id="count" type="number" min="1" max="5" value="1"></label><div></div></div><button class="primary" type="submit">Create proposal</button></form></div><div class="card"><h2>Workflow register</h2><p>${esc(tenant)} · isolated demo records</p>${view.workflows.length?view.workflows.map(w=>`<button class="workflow ${selected===w.requestId?'active':''}" data-id="${esc(w.requestId)}">${badge(pretty(w.state),tone(w.state))}<strong>${esc(w.agent)}</strong><small>${esc(w.requestId)}</small></button>`).join(''):'<p>No requests yet.</p>'}</div><p class="technical-note">These public demo identities do not authenticate real people. Revocation blocks future writes; it cannot undo effects already committed.</p></div><div>${detail(w)}</div></div>`;
$('#tenant').onchange=e=>perform(async()=>{tenant=e.target.value;selected=null;await refresh();});$('#role').onchange=e=>perform(async()=>{role=e.target.value;await refresh();});$('#refresh').onclick=()=>perform(refresh);
$('#new-workflow').onsubmit=e=>{e.preventDefault();const message=$('#message').value,count=Number($('#count').value);perform(async()=>{const result=await api('/v1/workflows',{requestId:'lab-'+crypto.randomUUID().slice(0,8),message,leadCount:count},token());selected=result.requestId;await refresh();status('Request created. Inspect its proposed action before approval.');});};
document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{selected=b.dataset.id;render();});if(!w)return;
if($('#ttl'))$('#ttl').onchange=e=>ttl=Number(e.target.value);if($('#limit'))$('#limit').onchange=e=>limit=Number(e.target.value);
async function operation(suffix,payload,custom=false){try{const result=await api(custom?`/api/control/${encodeURIComponent(selected)}/simulate`:`/v1/workflows/${encodeURIComponent(selected)}/${suffix}`,payload,token());status(result.notice||`${pretty(suffix)} completed. Inspect the state and record count.`);}finally{await refresh();}}
const bindings={approve:()=>operation('decision',{decision:'approve',actionDigest:current().authority.actionDigest,ttlSeconds:ttl,maxActions:limit}),reject:()=>operation('decision',{decision:'reject'}),execute:()=>operation('execute',{}),revoke:()=>operation('revoke',{}),cancel:()=>operation('cancel',{}),lost:()=>operation('simulate',{fault:'after_write'},true),timeout:()=>operation('simulate',{fault:'before_write'},true),revise:()=>operation('revise',{message:$('#revision-message').value,leadCount:Number($('#revision-count').value),revision:current().revision})};
for(const[id,fn]of Object.entries(bindings))if($('#'+id))$('#'+id).onclick=()=>perform(fn);$('#download').onclick=()=>download('workflow.json',current());}
export async function start(){await refresh();}
