import {$,esc,badge,metric,hero,api,perform,status,download,modelOptions,liveDisabled,refreshConfig} from '/shared/common.js';
let analysis,commentary=null;
const date=s=>new Date(s+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short'});
const sources=ids=>`<div class="sources">${ids.map(id=>`<a href="#source-${esc(id)}">${esc(id)}</a>`).join('')}</div>`;
function brief(items){return `<ul class="brief-list">${items.map(item=>`<li>${esc(item.text)}${sources(item.sources)}</li>`).join('')}</ul>`;}
function render(){const a=analysis,max=Math.max(a.forecast.duration,a.baseline.duration,1);$('#app').innerHTML=hero('02 / Programme Intelligence','See the consequence of a delay.','Trace a supplier scenario through an infrastructure programme, inspect the dependencies and prepare an evidence-linked decision brief.')+
`<div class="metrics">${metric('Baseline readiness',date(a.baseline.readyOn),`${a.baseline.duration} working days`)}${metric('Scenario readiness',date(a.forecast.readyOn),`${a.forecast.duration} working days`)}${metric('Programme impact',`+${a.delayDays} days`,'Working days; no holiday calendar')}${metric('Affected task finishes',a.affectedTasks.length,`Across ${new Set(a.forecast.tasks.filter(t=>a.affectedTasks.includes(t.id)).map(t=>t.workstream)).size} workstreams`)}</div>
<div class="card"><div class="card-head"><div><h2>${esc(a.programme)}</h2><p>A small, synthetic dependency model. Changing a scenario leaves the baseline intact.</p></div>${badge('Synthetic data','warn')}</div><form id="scenario" class="toolbar"><label>Task to delay<select id="task">${a.baseline.tasks.map(t=>`<option value="${esc(t.id)}" ${t.id===a.scenario.taskId?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>Additional working days<input id="delay" type="number" min="0" max="60" value="${a.scenario.delayDays}" required></label><button class="primary" type="submit">Calculate impact</button><button id="export" type="button">Download evidence pack</button></form></div>
<div class="card"><div class="card-head"><div><h2>Dependencies become visible.</h2><p>Finish-to-start calculation · start ${date(a.startDate)} · finish dates are readiness boundaries</p></div><div class="legend"><span><i class="swatch" style="background:#ccd7de"></i>Baseline</span><span><i class="swatch" style="background:#07958c"></i>Scenario</span><span><i class="swatch" style="background:#c58b2d"></i>Critical</span></div></div><div class="gantt-head"><span>Day 0</span><span>Day ${Math.round(max/2)}</span><span>Day ${max}</span></div>${a.forecast.tasks.map(t=>`<div class="gantt-row"><div class="gantt-name">${esc(t.name)}<small>${esc(t.workstream)} · ${t.float}d float ${t.finishDelta?`· +${t.finishDelta}d`:''}</small></div><div class="gantt-track" role="img" aria-label="${esc(t.name)}: baseline days ${t.baselineStart} to ${t.baselineFinish}; scenario days ${t.start} to ${t.finish}; ${t.critical?'critical':'non-critical'}"><span class="bar baseline" style="left:${t.baselineStart/max*100}%;width:${(t.baselineFinish-t.baselineStart)/max*100}%"></span><span class="bar forecast ${t.critical?'critical':''}" style="left:${t.start/max*100}%;width:${t.duration/max*100}%" title="${esc(t.owner)} · Ready ${t.readyOn}"></span></div></div>`).join('')}</div>
<div class="equal"><div class="card"><div class="card-head"><div><h2>Calculated decision brief</h2><p>Generated directly from the schedule and stated assumptions.</p></div>${badge('Deterministic','good')}</div>${brief(a.brief)}</div>
<div class="card"><div class="card-head"><div><h2>AI commentary</h2><p>Explain the calculated facts with source references.</p></div>${badge(commentary?'Live result':'Optional live AI','live')}</div><div class="toolbar"><label>Model<select id="model">${modelOptions()}</select></label><button id="generate" ${liveDisabled()?'disabled':''}>Generate AI commentary</button></div><p class="technical-note">This explicitly sends the synthetic scenario and calculated evidence to OpenAI. It makes one model call and may incur provider charges. AI cannot change the plan. Source-ID validation does not prove every sentence is correct.</p>${commentary?`<div class="live-output">${brief(commentary.items)}<p class="technical-note">${esc(commentary.model)} · ${(commentary.latencyMs/1000).toFixed(2)}s · ${commentary.usage.input_tokens??'—'} input / ${commentary.usage.output_tokens??'—'} output tokens</p></div>`:`<div class="empty"><strong>The calculation works without AI.</strong>${liveDisabled()?'Live generation is disabled or the session limit is reached.':'Generate commentary when you are ready to compare it with the calculated brief.'}</div>`}</div></div>
<div class="card"><h2>Evidence register</h2><p>Every briefing reference resolves to a visible source.</p>${a.sources.map(s=>`<article class="source" id="source-${esc(s.id)}"><strong>${esc(s.id)} · ${esc(s.title)}</strong><p>${esc(s.text)}</p></article>`).join('')}<details><summary>Inspect calculated task data and dependencies</summary><pre>${esc(JSON.stringify(a.forecast.tasks,null,2))}</pre></details></div>`;
$('#scenario').onsubmit=e=>{e.preventDefault();const payload={taskId:$('#task').value,delayDays:Number($('#delay').value)};perform(async()=>{analysis=await api('/api/programme/analyse',payload);commentary=null;render();status('Scenario calculated. The original baseline is unchanged.');});};
$('#export').onclick=()=>download('programme-evidence.json',{...analysis,aiCommentary:commentary});$('#generate').onclick=()=>{const model=$('#model').value;perform(async()=>{try{commentary=await api('/api/programme/brief',{scenario:analysis.scenario,model});status('Live commentary generated. Review it against the calculation and source register.');}finally{await refreshConfig();render();}});};}
export async function start(){analysis=await api('/api/programme');render();}
